services:
  lan-side-project:
    image: ${DOCKER_REGISTRY-}lansideproject
    build:
      context: lan-side-project
      dockerfile: Dockerfile
    container_name: lan-side-project
    restart: always
    depends_on:
      - postgres
      - keydb
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: ${REDIS_HOST:-keydb}
      REDIS_PORT: ${REDIS_PORT:-6379}
    volumes:
      - app-files:/app/files
      - app-logs:/app/logs

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - keydb-data:/data
    command: keydb-server /etc/keydb/keydb.conf --appendonly yes

volumes:
  app-files:
    driver: local
  app-logs:
    driver: local  
  postgres-data:
    driver: local
  keydb-data:
    driver: local
